In [10]:
import tensorflow as tf

In [8]:
tf.keras.losses.SparseCategoricalCrossentropy()



In [12]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## define the vocabulary size
voc_size=10000

In [18]:
### One Hot Representation

one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr
 

[[588, 6146, 5225, 6786],
 [588, 6146, 5225, 8131],
 [588, 448, 5225, 9704],
 [7631, 3917, 5206, 889, 1229],
 [7631, 3917, 5206, 889, 8596],
 [3211, 588, 6821, 5225, 2380],
 [3853, 4346, 4439, 889]]

In [15]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

In [19]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  588 6146 5225 6786]
 [   0    0    0    0  588 6146 5225 8131]
 [   0    0    0    0  588  448 5225 9704]
 [   0    0    0 7631 3917 5206  889 1229]
 [   0    0    0 7631 3917 5206  889 8596]
 [   0    0    0 3211  588 6821 5225 2380]
 [   0    0    0    0 3853 4346 4439  889]]


In [20]:
dim=10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.predict(embedded_docs)

1/1 [==============================] - 2s 2s/step


array([[[ 0.00967832, -0.01718905, -0.03636413,  0.04523826,
          0.03277812,  0.04943735, -0.01521339, -0.01762284,
         -0.01605619, -0.00977739],
        [ 0.00967832, -0.01718905, -0.03636413,  0.04523826,
          0.03277812,  0.04943735, -0.01521339, -0.01762284,
         -0.01605619, -0.00977739],
        [ 0.00967832, -0.01718905, -0.03636413,  0.04523826,
          0.03277812,  0.04943735, -0.01521339, -0.01762284,
         -0.01605619, -0.00977739],
        [ 0.00967832, -0.01718905, -0.03636413,  0.04523826,
          0.03277812,  0.04943735, -0.01521339, -0.01762284,
         -0.01605619, -0.00977739],
        [ 0.02146323,  0.04991794, -0.00626466, -0.00952288,
          0.04247444,  0.03983605, -0.02978774,  0.02871195,
          0.00131382,  0.03418512],
        [-0.0372386 ,  0.03741587,  0.01674166,  0.0450124 ,
          0.01598313,  0.03013479, -0.04388666, -0.01814672,
         -0.02510394,  0.01385132],
        [-0.00401799,  0.01751541,  0.01341242, -0.0